//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFindingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountFee
    {
        public int accountFeeID { get; set; }
        public System.DateTime paymentDate { get; set; }
        public int durationDay { get; set; }
        public double fee { get; set; }
        public int employeeID { get; set; }
    
        public virtual User User { get; set; }
    }
}
