//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFindingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobCategory> JobCategories { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PostFee> PostFees { get; set; }
        public virtual DbSet<PostReport> PostReports { get; set; }
        public virtual DbSet<RequestedList> RequestedLists { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<AccountFee> AccountFees { get; set; }
        public virtual DbSet<Conversation> Conversations { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
