//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFindingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostReport
    {
        public System.DateTime reportDate { get; set; }
        public string reportType { get; set; }
        public string comment { get; set; }
        public int reportByEmployee { get; set; }
        public int reportedPost { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
