//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFindingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedList
    {
        public int requestedPostID { get; set; }
        public int requestedEmployeeID { get; set; }
        public double wage { get; set; }
        public System.DateTime requestedDate { get; set; }
        public Nullable<System.DateTime> confirmedDate { get; set; }
        public string status { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
