//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFindingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int settingID { get; set; }
        public string title { get; set; }
        public string settingStringLong { get; set; }
        public string settingStringShort { get; set; }
        public Nullable<double> settingStringDouble { get; set; }
        public Nullable<int> settingStringInt { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> modifiedByUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
