//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFindingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int skillID { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string proficiency { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public int employeeID { get; set; }
        public int jobCategoryID { get; set; }
    
        public virtual JobCategory JobCategory { get; set; }
        public virtual User User { get; set; }
    }
}
